#!/usr/bin/env bash
set -euo pipefail

# One-time setup: wrap clawhub install with skill-check enforcement.
# Adds a shell function to ~/.bashrc and ~/.zshrc.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SAFE_INSTALL="$ROOT_DIR/scripts/safe_install.sh"

if [[ ! -x "$SAFE_INSTALL" ]]; then
  chmod +x "$SAFE_INSTALL"
fi

read -r -d '' SNIPPET <<EOF || true
# >>> skill-check guard >>>
# Auto-generated by skill-check/scripts/install_shell_guard.sh
clawhub() {
  if [[ "\$1" == "install" ]]; then
    shift
    "${SAFE_INSTALL}" "\$@"
  else
    command clawhub "\$@"
  fi
}
# <<< skill-check guard <<<
EOF

install_into_rc() {
  local rc_file="$1"
  touch "$rc_file"
  if grep -q "skill-check guard" "$rc_file"; then
    echo "[skip] guard already present in $rc_file"
    return
  fi
  printf "\n%s\n" "$SNIPPET" >> "$rc_file"
  echo "[ok] added guard to $rc_file"
}

install_into_rc "$HOME/.bashrc"
install_into_rc "$HOME/.zshrc"

echo
echo "Guard installed. Open a new shell (or run: source ~/.bashrc)"
echo "After that, 'clawhub install <slug>' will be enforced via skill-check."
